### ISSUE TITLE
Add https certificate 

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint.io#10]
https://letsencrypt.org/

**Comment by ntwb** [comment]
GitHub pages do not currently support adding Lets Encrypt certificates.

Some references:
• https://gist.github.com/coolaj86/e07d42f5961c68fc1fc8
• https://github.com/isaacs/github/issues/156

**Comment by MoOx** [comment]
You can try Cloudflare free plan (like I did for https://phenomic.io)

**Comment by coliff** [comment]
I've also successfully used the free Cloudflare plan on a Github-hosted site. it was simple and quick to do. I used the instructions from here to guide me: https://www.benburwell.com/posts/configuring-cloudflare-universal-ssl/

**Comment by jeddy3** [comment]
@coliff Thanks for the link!

If someone finds time to pick this up, I'm sure that link will be useful.

**Comment by hudochenkov** [comment]
https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/ Official CloudFlare guide.

**Comment by jeddy3** [comment]
@hudochenkov As a member of the stylelint org you have access to all the repos, this one included. :) So, feel free to give the the cloudflare stuff a shot. It's an itch I'd love to see scratched, I've not had time though.

**Comment by hudochenkov** [comment]
It's alive! https://stylelint.io/

There's one small thing. Readme had an image loaded over HTTP (it's [fixed](https://github.com/stylelint/stylelint/commit/fa85eae4c2b2e30f0f47e82a78f1799a60b95497) now). Since content for a website taken from `node_modules`, and we need to wait for a new stylelint release to fix this tiny problem. I decided to do [a little trick](https://github.com/stylelint/stylelint.io/blob/a3f391ad7cdc598bc13062d5e5b78fff3ad3f7eb/scripts/copy-stylelint-docs.js#L20-L23). Hope it's ok :)

**Comment by ntwb** [comment]
> It's alive! https://stylelint.io/

Yay, cool 🎉 

> (it's fixed now).

Can you create pull requests in future please, when using _git blame_ it's helpful to be able to track everything back to any discussion, currently there are no links in those commits back to this discussion, thanks.

**Comment by hudochenkov** [comment]
Sorry about that. It was one letter typo fix.

**Comment by ntwb** [comment]
> Sorry about that. It was one letter typo fix.

Yup, it should still be reviewed though 😄 , see https://github.com/stylelint/stylelint/issues/1663#issuecomment-274260021 

> I decided to do a little trick. Hope it's ok :)

Also, [that code](https://github.com/stylelint/stylelint.io/blob/master/scripts/copy-stylelint-docs.js#L20-L23) added per the above needs to be removed as part of the `7.7.2` or `8.0.0` release, do you want to create a new issue for this please @hudochenkov so it does not get forgotten about

**Comment by hudochenkov** [comment]
@ntwb I agree, shouldn't rush ever again. Thank you for reminding me!  :)

**Comment by jeddy3** [comment]
Woohoo! Thanks for doing this @hudochenkov!
