### ISSUE TITLE
Dead link to https://github.com/shinnn/vscode-stylelint

### ISSUE THREAD

**Issue by art-in** [stylelint/stylelint.io#119]
https://stylelint.io/user-guide/complementary-tools#editor-plugins

"[vscode-stylelint](https://github.com/shinnn/vscode-stylelint): A Visual Studio Code extension for stylelint."

**Comment by hudochenkov** [comment]
Thanks!

Closing as a duplicate for https://github.com/stylelint/stylelint/pull/4478
