### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by ai** [stylelint/stylelint.io#12]
Favicon is very important, because users use them to find link in bookmarks. Also you should add OpenGraph image, because it is very important for pormotion.

You can take favicons sizes from postcss.org website: https://github.com/postcss/postcss.org/tree/9fbc10c0b756e970176edbf57c6c8a3aba408a13/web_modules/LayoutContainer
* 48×48 `favicon.ico`
* 192×192 for touch devices
* 1200×630 for OpenGraph

**Comment by ntwb** [comment]
Sounds good 👍
