### ISSUE TITLE
Fix missing 'valid-pattern' class for font-family-no-missing-generic-family-keyword

### ISSUE THREAD

**Issue by freethebit** [stylelint/stylelint.io#120]
> Clearly describe the documentation issue

At this link: https://stylelint.io/user-guide/rules/font-family-no-missing-generic-family-keyword

the last 2 `pre` are missing `valid-pattern` class. The document describe as valid.

> What solution would you like to see?

Add `valid-pattern` to these two `pre`.

**Comment by fanich37** [comment]
Thank you for the report 👍 
I transferred this issue here since it's about the doc and not about `stylelint` itself.

**Comment by ybiquitous** [comment]
`valid-pattern` class is applied by the following JS:

https://github.com/stylelint/stylelint.io/blob/966962a5c3c507c2fad412312dd3baf7c80ac316/website/static/js/pattern-validity.js#L2-L9

It seems good to fix the document's descriptions to match the patterns above:

https://github.com/stylelint/stylelint/blob/a20b05f934f34c0306b286ca3aec30c2de8ca611/lib/rules/font-family-no-missing-generic-family-keyword/README.md
