### ISSUE TITLE
Enable invite-contributors in this repository

### ISSUE THREAD

**Issue by imbsky** [stylelint/stylelint.io#126]

**Comment by imbsky** [comment]
I sent a request to other members.

**Comment by jeddy3** [comment]
Is this needed if we have invite-contributors for the main repo?

**Comment by ntwb** [comment]
I don't believe we need this on any repo except the maiin repo

If we have or get contributors with specific focuses outside of the normal stylelint type code issues we can manually add users as required

**Comment by imbsky** [comment]
I originally opened it because I thought all the documents were here, but since the documents are also in the main repository, I agree to close it.
