### ISSUE TITLE
About locked issues

### ISSUE THREAD

**Issue by imbsky** [stylelint/stylelint.io#127]
Some of the issues I have opened have been locked down by one maintainer and can only be discussed by members. Also, I was suddenly removed from the organization. (Well, that being said, I did something that wasn't very cool.) If you continue the discussion, you should unlock it. and if you don't discuss it, close it. Now those issues are really meaningless.

**Comment by imbsky** [comment]
Also, as @ybiquitous said, Docusaurus v2 is still in alpha but already stable. Of course, I will respect your opinion.

**Comment by imbsky** [comment]
@hudochenkov Can you please either unlock or close those?

**Comment by jeddy3** [comment]
> I have opened have been locked down by one maintainer and can only be discussed by members. Also, I was suddenly removed from the organization. 

I can explain this to you @imbsky.

The maintainer revoked your access and locked the issues to ensure nothing untoward was occurring. It is customary within the stylelint organisation for actions to be discussed first. When an action was taken without discussion, the maintainer locked things down. This was a prudent thing to do as there are bad actors around.

We're now sure nothing untoward occurred. Your access has been reinstated and your contributions are very welcome. The issues are now unlocked too.

I think this event is also a reflection of our documentation. As such, I've created a pull request 
 (https://github.com/stylelint/stylelint/pull/4548) to restructure it, including pulling the docs about "Managing issues", "Performing releases" and "Reviewing pull requests"  into their own Maintainer guide.

**Comment by imbsky** [comment]
Now, I can understand. But I felt something doesn't feel right about not doing it for a few days even though he said he would explain it. Anyway, that makes sense. Thank you for your explanation.

**Comment by ntwb** [comment]
Apologies, work and real life gets in the way occasionally

Cheers,

Stephen Edgar
________________________________
