### ISSUE TITLE
Improve visible readability of wrong/correct syntax examples

### ISSUE THREAD

**Issue by Nirazul** [stylelint/stylelint.io#13]
This is a copy/paste from the closed issue over at stylelint. I'm gonna look into it myself in the next days and will report, what I have found out. :)

> I'm just linking to a (solved) issue I've created some time ago over at eslint:
eslint/eslint.github.io#108

> It's about visually improving code blocks that are currently hard to read whether they are correct examples or failing examples, creating warnings.

> I'm not sure how the documentation on the homepage is created, but maybe the solution found on this issue could point you in the right direction.

**Comment by jeddy3** [comment]
> I'm gonna look into it myself in the next days and will report, what I have found out. :)

Fantastic!

We use [Phenomic](https://phenomic.io/) behind the scenes. The [process](https://github.com/stylelint/stylelint.io/blob/master/package.json#L7-L23) goes something like:

1. [Copy](https://github.com/stylelint/stylelint.io/blob/master/scripts/copy-stylelint-docs.js) all the markdown files out of the `node_modules/stylelint/*` directory.
2. [Process](https://github.com/stylelint/stylelint.io/blob/master/scripts/process-stylelint-docs.js) those files so the are compatible with Phenomic e.g. automatically generate the mandatory front matter, and fix the links between documents.
3. Generate the HTML of the static build using Phenomic.

Perhaps there is scope at the second stage to calculate which examples show correct patterns, and those that don't, and then add some extra mark-up?

Good luck and thanks for looking into this :)
