### ISSUE TITLE
Add config wizard

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint.io#19]
Ref: https://github.com/stylelint/stylelint/issues/1622

**Comment by ai** [comment]
Done https://maximgatilin.github.io/stylelint-config/

**Comment by jitendravyas** [comment]
Another one https://boldyrev-d.github.io/stylelint-config-generator/

**Comment by ai** [comment]
@jeddy3 any updates? We already have the good generator but it is hard to find it for most of the users. Maybe we should add the link to https://stylelint.io/user-guide/rules/ ?

**Comment by jeddy3** [comment]
> Maybe we should add the link to https://stylelint.io/user-guide/rules/ ?

SGTM. The file for the contents of the rules page is at: https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md

**Comment by jeddy3** [comment]
Closing in favour of advocating the use of stylelint-config-standard, which we [now do in our getting started section](https://stylelint.io/user-guide/get-started).

We can add links to the generators to [awesome-stylelint](https://github.com/stylelint/awesome-stylelint).
