### ISSUE TITLE
Fix white scrollbar for dark mode on Firefox

### ISSUE THREAD

**Issue by vitaly-zdanevich** [stylelint/stylelint.io#199]
Current problem:

![image](https://user-images.githubusercontent.com/3514015/124048100-4071b580-da1e-11eb-84e9-41e1c149aca5.png)

You can use this code:
```
:root {
    scrollbar-color: #333 #000;
}
```
That will render to this:
![image](https://user-images.githubusercontent.com/3514015/124048271-9b0b1180-da1e-11eb-9957-72ddc10c8fcf.png)

I can make a pull request but I do not know what file to edit.

**Comment by jeddy3** [comment]
@vitaly-zdanevich Thanks for the report.

I've just updated to website the latest beta of [Docusaurus](https://docusaurus.io/). If that hasn't fixed the issue, can you report the issue [upstream](https://github.com/facebook/docusaurus/issues) and send a pull request there.

We're using [the classic theme](https://github.com/facebook/docusaurus/tree/master/packages/docusaurus-theme-classic) (with just a sprinkling of custom styles for [two features we added](https://github.com/stylelint/stylelint.io/blob/master/src/css/custom.css)), so bug fixes are best done upstream.

I'll close this issue in our tracker.
