### ISSUE TITLE
Add demo linter

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint.io#2]
Useful as a demo and for testing. 

Perhaps similar to how [`eslint` does it](http://eslint.org/demo/) i.e. 3 panels: input, output and config. For ease-of-implementation we could just have text area for the config panel. Its initial state would be the config copied out from the `stylelint-config-standard` module.

`postcss-cssnext` [has a react-based demo](https://github.com/MoOx/postcss-cssnext/tree/master/docs/src/modules/playground) that would provide great inspiration.

**Comment by m-allanson** [comment]
Heavily inspired by the links above, here's a demo: http://m-allanson.github.io/stylelint-browser-demo/
And here's the source: https://github.com/m-allanson/stylelint-browser-demo

It's using webpack to stub out code that expects access to a filesystem (thanks to @TrySound for suggesting that approach).

It could clearly do with some design and UX love, which I'd be happy to spend a bit of time on. 

Any feedback is welcome!

**Comment by jeddy3** [comment]
Looking great!

Do you want to see if you can integrate what you've done so far into the `react` app that powers the site? You should have access to this repo too and so you can create a branch/PR for it.

I suspect you'll need to add a new layout here (perhaps called "Demo"): https://github.com/stylelint/stylelint.io/tree/master/web_modules/layouts

I guess similar to how we did it over in the postcss.org repo:
https://github.com/postcss/postcss.org/tree/master/web_modules/layouts/HomePage

You might need to programmatically generate the `content/demo/index.md` file somewhere in here, as we clean out the `content` folder when we generate the site:
https://github.com/stylelint/stylelint.io/blob/master/scripts/copy-stylelint-docs.js

So that it looks something like this:
https://github.com/postcss/postcss.org/blob/master/content/index.md

And the webpack config is here: https://github.com/stylelint/stylelint.io/blob/master/scripts/webpack.config.client.js

What do you think? Fancy getting stuck into some `react` and `statinamic` goodness?

**Comment by m-allanson** [comment]
That sounds like a good next step, I'll see if I can work up a PR.

**Comment by davidtheclark** [comment]
@m-allanson With webpack stubbing out `fs`, did you not have to make any modifications at all to the stylelint code?

**Comment by davidtheclark** [comment]
Very cool! 

If you want to dig deeper, my only suggestions are about styling and UX, and I don't know how feasible. Here's what I'd love to see in order of priority:

- Syntax highlighting in both CSS and config
- Line numbers in the CSS
- Ability to write YAML config
- Some text editor features in the CSS (e.g. when you create an opening brace, it adds a closing brace)

You might be able to get the YAML config by the js-yaml package to parse the config. It should understand both YAML and JSON.

For the other things I'm not really sure because I haven't built an online text editor myself :) But I think there are tools out there worth looking into that might make it easy. ?

**Comment by m-allanson** [comment]
@davidtheclark Nope, no stylelint modifications were needed! The simplified config and plugin requirements mean stylelint doesn't hit `fs` related code except when importing certain modules. There's [a dummy module](https://github.com/m-allanson/stylelint-browser-demo/blob/master/site/empty-module.js) which replaces stylelint's [`fs`-dependent dependencies](https://github.com/m-allanson/stylelint-browser-demo/blob/master/webpack.config.babel.js#L14-L20). There may be a more robust or efficient approach for handling this, I'm all ears if anyone has suggestions :) 

Those features sound useful, I agree we should be able to use existing tools for some of them. My personal wishlist includes the ability to share code and configs via URL, but I think that's a long way down the line. See the [Save and Fork buttons on AST Explorer](http://astexplorer.net/#/np0DfVT78g/1) for an example.

I can work towards getting a basic demo linter integrated with stylelint.io.  Once that's done we could create another issue for improvements?

**Comment by davidtheclark** [comment]
Yeah, that all sounds great. Nice work.

**Comment by cbrwizard** [comment]
Hey, how about adding an option to autoformat given styles with 'stylefmt', since now it supports stylelint? I think it might be useful for users to see how their styles are going to be formatted by it.

**Comment by m-allanson** [comment]
Here's a new demo linter: http://stylelint-demo.herokuapp.com/

The source is here: https://github.com/m-allanson/stylelint-demo

This version does away with the complicated webpack monkeypatching setup from the previous PR, instead stylelint is running behind a web server in a standard node environment. The frontend basically uses the same React components as before.

If this looks like a good approach it could be included as a link from the docs or embedded into the stylelint site via an iframe.

**Comment by jeddy3** [comment]
This is awesome! 👍 👍 

> it could be included as a link from the docs or embedded into the stylelint site via an iframe.

Which do you think is best? Do you think it'll be easy to knock-up a PR with an iframe or is the content generation from the stylelint markdown files going to complicate things?

**Comment by m-allanson** [comment]
An iframe looks like it'll work but there's some issues with sizing it correctly. I'll push up another PR once I've got that working neatly.

**Comment by ntwb** [comment]
This. Is. Awesome. 💥

**Comment by davidtheclark** [comment]
Very nice @m-allanson!

I'll try to poke around a bit more this weekend. But one suggestion so far: I think it might be nice to have the config and code in horizontal (side-by-side) panels instead of vertical panels. Because CSS is usually pretty narrow, we probably don't need the full browser width for the code. And that way adding or subtracting warnings would not bounce the config.

**Comment by ntwb** [comment]
> I think it might be nice to have the config and code in horizontal (side-by-side) panels instead of vertical panels.

PostCSS' RTLCSS does side-by-side http://rtlcss.com/playground/

**Comment by jeddy3** [comment]
> PostCSS' RTLCSS does side-by-side http://rtlcss.com/playground/

I think that's because, for RTLCSS, it's input css (frequent) → output css (frequent) .

We have input config (infrequent) + input css (frequent) → output warnings (frequent). 

http://eslint.org/demo/ stacks them in the same order as we currently do:

1. input css
2. output warnings
3. input config

The only difference is they pull the input css and the output warnings side-by-side when there's enough screen real-estate. We can easily add that enhancement to our mobile-first code though :)

**Comment by m-allanson** [comment]
I've tweaked the demo layout based on the comments above, now the code and results panels will display side-by-side when there's enough space (as per @jeddy3's suggestion). I'd be happy to see any improvements and alternative layouts though.

There's also a new PR here which adds a 'Demo' route to stylelint.io.

**Comment by jeddy3** [comment]
Done in #20

@m-allanson 🎉
