### ISSUE TITLE
Links in navigation bar are small and hard to hover/click

### ISSUE THREAD

**Issue by Calinou** [stylelint/stylelint.io#27]
The links in the navigation bar are quite small (font size) and hard to hover and click (lack of padding).

![links](https://cloud.githubusercontent.com/assets/180032/20554390/ee183722-b15b-11e6-9dfc-55bcc3b4a456.png)

**Comment by jeddy3** [comment]
@Calinou Thank you for the suggestion. I intend to update the design very soon and will address this issue then.
