### ISSUE TITLE
Uneven spacing in navigation items

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint.io#29]
Found in #28:

<img width="538" alt="screen shot 2016-11-25 at 3 27 04 pm" src="https://cloud.githubusercontent.com/assets/628431/20636079/b0266e1a-b323-11e6-8d08-20b6506a49ce.png">

I think if the logic here is that rules, plugins, etc. are part of the User Guide, it's not really transparent enough; so the spacing variation looks more like a bug to me than a feature. Does that make sense?

**Comment by jeddy3** [comment]
> I think if the logic here is that rules, plugins, etc. are part of the User Guide

Yep :)

> it's not really transparent enough; so the spacing variation looks more like a bug

Agreed.
