### ISSUE TITLE
Post-update discussion

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint.io#3]
@davidtheclark As you saw, I pushed up an update to website last night that brings, the long-awaited, proper urls :) I figured I'd quickly give you the lowdown about the change.

The first thing to say is that I've built this repo on top of the excellent work the guys are putting in on the [postcss.org repo](https://github.com/postcss/postcss.org). I figured this would save us a bundle of time!

Our particular approach is that this repo consumes the `stylelint` module, it then:

* Generates, with the help of [statinamic](https://github.com/MoOx/statinamic) and @nicinabox initial work (thanks again!), a static website from the docs within the module.
* Dog-foods the module to lint the CSS of the static website.
* (In the future it will) make use of the module for the online demo linter.

I did this to keep the main `stylelint` repo as clean as possible. The website requires a number of dependencies that I figured would be best kept separate from those of the tool itself.

[statinamic](https://github.com/MoOx/statinamic) is being [very actively developed](https://github.com/MoOx/statinamic/pulls?q=is%3Apr+is%3Aclosed) at the moment, and so the I'm tracking both the changes there and in the postcss.org repo. So lots of little improvements should be forthcoming.

Any feedback? If not, I'll close this issue.

**Comment by davidtheclark** [comment]
@jeddy3 Great work! I did check out the website and it is much improved. And since we didn't have to change out documentation patterns to get it that way, seems like the mission has been fulfilled.
