### ISSUE TITLE
Add "Rules" link to page header

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint.io#309]
### What is the problem you're trying to solve?

I think people often visit the ["Rules"](https://stylelint.io/user-guide/rules) page on the website. But, it would be inconvenient since there is no link to the "Rules" page in the page header.

<img width="314" alt="image" src="https://user-images.githubusercontent.com/473530/226356244-e4c8ec1b-5b41-4feb-900e-a150b1a5e787.png">

### What solution would you like to see?

So, I suggest adding a link to the "Rules" page in the page header. I think the following possible ways:

- Add a "Rules" link
- Replace the "Docs" link with a new "Rules" link to avoid increasing items in the header
  - we might remove duplicates because the "Docs" link and the Stylelint logo link point to the same URL.

**Comment by mattxwang** [comment]
I agree with this idea! I think just adding "Rules" (without removing "Docs") makes the most sense to me.

**Comment by ybiquitous** [comment]
@mattxwang Thanks for the feedback!

I've labeled the issue as **ready to implement**. Please consider [contributing](https://stylelint.io/contributing) if you have time.
