### ISSUE TITLE
Translate the document into Chinese

### ISSUE THREAD

**Issue by molee1905** [stylelint/stylelint.io#33]
hi,there

i do really appreciate all the effort that stylelint team has made and the stylelint is one of the best linter for css.  During the period of learning and using it, a thought comes into my mind: provide a Chinese version to let more and more developers who are speaking Chinese use and be familiar with it, so, i'm here asking for the permission to publish it on http://stylelint.cn (translation undergoing 80% which now mixes English and Chinese).

**Comment by davidtheclark** [comment]
Sounds excellent @molee1905! I'm sure other Chinese speakers will be very grateful for your effort! And it's exciting for us to expose stylelint to more people.

**Comment by ntwb** [comment]
We should find a suitable location on our English docs site to link the these Chinese docs 💯

**Comment by jeddy3** [comment]
@molee1905 Fantastic stuff :)

> We should find a suitable location on our English docs site to link the these Chinese docs

We could link to it from the main repo docs so it's discoverable outside of the website too.
