### ISSUE TITLE
Feature: Scroll to top

### ISSUE THREAD

**Issue by bilalmirza74** [stylelint/stylelint.io#351]
### What is the problem you're trying to solve?

After reaching the footer, instead of scrolling back up by rotating the mouse wheel or swiping on mobile, we can simply click on the scroll-to-top button.

### What solution would you like to see?

Adding Scroll to Top Button
will improve UX/UI

![image](https://github.com/stylelint/stylelint/assets/84387676/edfd8bb9-18f4-4ec4-8c07-7c48055e0e68)

**Comment by ybiquitous** [comment]
@bilalmirza74 The "Scroll to top" button has been implemented already. The button appears when you scroll the page to the top.

<img width="546" alt="image" src="https://github.com/stylelint/stylelint.io/assets/473530/856b4771-29a5-4419-9c49-266d628c159a">
