### ISSUE TITLE
Auto change of site theme depending on system/browser theme

### ISSUE THREAD

**Issue by rakleed** [stylelint/stylelint.io#361]
### What is the problem you're trying to solve?

If I have a dark theme selected on my system, then when I first open the docs, the light theme of the site is displayed, which is very unpleasant for the eyes.

### What solution would you like to see?

Automatic change of site theme depending on the system/browser theme by default.

**Comment by jeddy3** [comment]
@rakleed Thanks for the request and for using the template.

SGTM.

You're welcome to send a PR. It's a [minor configuration change](https://docusaurus.io/docs/api/themes/configuration#respectPrefersColorScheme).

(Issue transferred).
