### ISSUE TITLE
Fix favicon is not visible when using dark theme on system/browser

### ISSUE THREAD

**Issue by rakleed** [stylelint/stylelint.io#362]
### What is the problem you're trying to solve?

`favicon` is not visible when using a dark theme on the system/browser.

![CleanShot 2023-11-13 at 22 04 03](https://github.com/stylelint/stylelint/assets/19418601/caeeef0f-232c-4bf9-a148-15ec65ff384f)

### What solution would you like to see?

https://stackoverflow.com/q/55170708/11336855

**Comment by jeddy3** [comment]
@rakleed Thanks for the report.

We may need to wait for a fix upstream. However, you're welcome to look into it.

https://docusaurus.io/docs/api/docusaurus-config#favicon

**Comment by rakleed** [comment]
https://github.com/facebook/docusaurus/issues/4954#issuecomment-860258531

**Comment by jeddy3** [comment]
SVG icon with media query to detect preference SGTM. You're welcome to open a PR.
