### ISSUE TITLE
Add arrow navigation between rules

### ISSUE THREAD

**Issue by ai** [stylelint/stylelint.io#37]
@Seminioni suggested a nice idea: listen arrows key press in rule page and open next/prev rule.
https://twitter.com/andreysitnik/status/861958363751612417

@davidtheclark approved idea.

I will use this issue to send developers to fix it (if you need help).

**Comment by binjospookie** [comment]
https://github.com/stylelint/stylelint.io/pull/38

**Comment by binjospookie** [comment]
Merged

**Comment by jeddy3** [comment]
@binjospookie Thanks. Done in #38.

We'll push the changes live with the next stylelint release.

**Comment by binjospookie** [comment]
@jeddy3 thank you for code-review!
