### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint.io#4]
I am unable to deploy the latest version of the docs. I am being told that authentication fails, despite knowing that I am using the right credentials.

**Comment by MoOx** [comment]
Can you show the entire error?
I would say it's related to gh-pages modules.
Due to issue with repo site (single line html produce brutal diff, so repo can becoming big easily), I recently change the technique for deploy, by using a simple script that just force push dist to the gh-pages branch.

Here it is https://github.com/putaindecode/putaindecode.io/blob/d3cb4d185066668ce473b139ab671e234c51d0a4/scripts/deploy.sh

**Comment by davidtheclark** [comment]
Here's the log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.7.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy' ]
2 info using npm@3.8.0
3 info using node@v5.7.1
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle stylelint.io@~predeploy: stylelint.io@
6 verbose lifecycle stylelint.io@~predeploy: unsafe-perm in lifecycle true
7 verbose lifecycle stylelint.io@~predeploy: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/davidclark/dev/stylelint.io/node_modules/.bin:/usr/local/Cellar/node/5.7.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
8 verbose lifecycle stylelint.io@~predeploy: CWD: /Users/davidclark/dev/stylelint.io
9 silly lifecycle stylelint.io@~predeploy: Args: [ '-c', 'npm run build' ]
10 silly lifecycle stylelint.io@~predeploy: Returned: code: 0  signal: null
11 info lifecycle stylelint.io@~deploy: stylelint.io@
12 verbose lifecycle stylelint.io@~deploy: unsafe-perm in lifecycle true
13 verbose lifecycle stylelint.io@~deploy: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/davidclark/dev/stylelint.io/node_modules/.bin:/usr/local/Cellar/node/5.7.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
14 verbose lifecycle stylelint.io@~deploy: CWD: /Users/davidclark/dev/stylelint.io
15 silly lifecycle stylelint.io@~deploy: Args: [ '-c',
15 silly lifecycle   'gh-pages -d dist -r https://github.com/stylelint/stylelint.github.io.git -b master' ]
16 silly lifecycle stylelint.io@~deploy: Returned: code: 1  signal: null
17 info lifecycle stylelint.io@~deploy: Failed to exec deploy script
18 verbose stack Error: stylelint.io@ deploy: `gh-pages -d dist -r https://github.com/stylelint/stylelint.github.io.git -b master`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
18 verbose stack     at emitTwo (events.js:100:13)
18 verbose stack     at EventEmitter.emit (events.js:185:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
18 verbose stack     at emitTwo (events.js:100:13)
18 verbose stack     at ChildProcess.emit (events.js:185:7)
18 verbose stack     at maybeClose (internal/child_process.js:827:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
19 verbose pkgid stylelint.io@
20 verbose cwd /Users/davidclark/dev/stylelint.io
21 error Darwin 15.3.0
22 error argv "/usr/local/Cellar/node/5.7.1/bin/node" "/usr/local/bin/npm" "run" "deploy"
23 error node v5.7.1
24 error npm  v3.8.0
25 error code ELIFECYCLE
26 error stylelint.io@ deploy: `gh-pages -d dist -r https://github.com/stylelint/stylelint.github.io.git -b master`
26 error Exit status 1
27 error Failed at the stylelint.io@ deploy script 'gh-pages -d dist -r https://github.com/stylelint/stylelint.github.io.git -b master'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the stylelint.io package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     gh-pages -d dist -r https://github.com/stylelint/stylelint.github.io.git -b master
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs stylelint.io
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls stylelint.io
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]

**Comment by MoOx** [comment]
Hum does not provide useful information...

Do you have node_modules/.bin/gh-pages file ?
Can you try to reinstall node_modules?

Otherwise no idea... :/

**Comment by davidtheclark** [comment]
I think it might have to do with the fact that I turned on two-factor authentication yesterday? I tried generating a new personal access token and exposing it at `GITHUB_TOKEN`, but got the same results. @MoOx any idea if I'm missing some step related to using https to deploy when you have 2FA?

**Comment by MoOx** [comment]
You are not supposed to have a token if you deploy locally. I use ssh key for github (no problem with 2FA tho).

Exposing the GITHUB_TOKEN only make sense for CI. 

Did you read this? http://moox.io/statinamic/docs/usage/gh-pages/

**Comment by davidtheclark** [comment]
Ah. Others had written a script using the repo's https URL to deploy, but I just replaced that with the ssh URL and it worked. Thanks @MoOx.
