### ISSUE TITLE
Add ToC to each page except for home

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint.io#42]
Ref: https://github.com/stylelint/stylelint/issues/2668

We might be able to make use of something like [remark-toc](https://github.com/wooorm/remark-toc) to autogenerate.

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint.io/pull/54

**Comment by hudochenkov** [comment]
It's not really done:

> For other pages [not rules pages] we need to add  in markdown in stylelint repository.

I'll do it later.
