### ISSUE TITLE
Fix "Search Results: Display 'No Results Found'" Message Instead of 'undefined'

### ISSUE THREAD

**Issue by damiansire** [stylelint/stylelint.io#438]
### Describe the documentation issue

When you search for something and it finds nothing in the documentation, show the message: " Try searching for: **undefined** "

![image](https://github.com/user-attachments/assets/1a602dac-34f7-47b4-bc1a-a2e1121507a9)

### What solution would you like to see?

Display 'No Results Found' or something other Message Instead of 'undefined'

**Comment by ybiquitous** [comment]
@damiansire Thanks for the report. I've transferred this issue to the website repository.

**Comment by ybiquitous** [comment]
Here is the current algolia config:
https://github.com/stylelint/stylelint.io/blob/eaa0978250a275c6d4ac71e137338bf7c016a65c/docusaurus.config.js#L77-L81

**Comment by ybiquitous** [comment]
I've updated the Algolia index configuration according to the following docs:
- https://docsearch.algolia.com/docs/templates/#docusaurus-v2--v3-template
- https://docusaurus.io/docs/search#algolia-index-configuration

I added `lvl0` to the index config:

<img width="238" alt="image" src="https://github.com/user-attachments/assets/6d7761f3-cee8-4ae5-9855-a256556d134d">

Then, the suggestions increased, but `undefined` still remains:
<img width="235" alt="image" src="https://github.com/user-attachments/assets/d4494012-b11d-4a1b-9f11-34f0092e3a11">

However, the same issue happens also in <https://docusaurus.io>, so I guess it's a problem with a UI component of Docusaurus or Algolia. 🤔 

<img width="591" alt="image" src="https://github.com/user-attachments/assets/0896687f-5a2d-46ef-aabf-47cdaa061640">

**Comment by jeddy3** [comment]
Looks like it was fixed upstream:

<img width="568" alt="Image" src="https://github.com/user-attachments/assets/a2e47222-2802-4ae6-8e9d-445303de001a" />
