### ISSUE TITLE
Should use phenomic 404 page

### ISSUE THREAD

**Issue by amirhouieh** [stylelint/stylelint.io#44]
Hi, was just getting my head around Phenomic by looking at stylelint.io code, notice that 404 page layout not working. It is a simple fix so not sure if it makes sense to send a pull request for it thought. any way problem happens at `../layouts/Page/index.js` and my quick fix was adding this at the beginning  of render function:
```
...
if(!head){
    return (
      <div className={ styles.page }>
        { children }
      </div>
    )
}
...
```

**Comment by jeddy3** [comment]
@amirhouieh Thanks for spotting the 404 page not working. If you find a moment, could you send over a PR with your fix please?
