### ISSUE TITLE
Replace https with ssh

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint.io#5]
@jeddy3 Any objections to replacing the https URL with the ssh URL in `    "deploy": "gh-pages -d dist -r https://github.com/stylelint/stylelint.github.io.git -b master"`?

(Would be `gh-pages -d dist -r git@github.com:stylelint/stylelint.github.io.git -b master`)

**Comment by jeddy3** [comment]
Sgtm :)
