### ISSUE TITLE
processLinks.js breaks some links

### ISSUE THREAD

**Issue by m-allanson** [stylelint/stylelint.io#6]
Following on from https://github.com/stylelint/stylelint/issues/944, I noticed that there is another broken link. 

At http://stylelint.io/developer-guide/rules/#write-the-rule, the `PostCSS API` link has an href of `https://github.com/postcss/postcss/blob/master/api`. This is a 404 because `docs` and `.md` have been stripped from the original url.

The original url in https://raw.githubusercontent.com/stylelint/stylelint/master/docs/developer-guide/rules.md is `https://github.com/postcss/postcss/blob/master/docs/api.md` 

Could `processLinks.js` be updated to be more selective about which links are processed?

**Comment by jeddy3** [comment]
> Could processLinks.js be updated to be more selective about which links are processed?

Very much so. It's the weak link in an otherwise solid system.
