### ISSUE TITLE
Google Analytics not receiving data

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint.io#60]
> First detected: Aug 28, 2018 8:15:00 PM
>>
>> Property stylelint.io is not receiving hits. Either your site is not receiving any sessions or it is not tagged correctly.
>>
>> Google Tag Assistant Recordings can help you ensure that your site is tagged correctly.
>>
>> https://support.google.com/analytics/answer/1008080?hl=en

Not sure why I didn't receive an email for this, to either my personal email or the style lint email /shrug

**Comment by hudochenkov** [comment]
Indeed, I don't see in a console that any request is sent to GA server.

Maybe it's a good thing, because of the GDPR we need to request the user's consent for tracking.

**Comment by jeddy3** [comment]
> Maybe it's a good thing, because of the GDPR we need to request the user's consent for tracking.

Good point. I don't think we've garnered any value from having analytics so far, so I think we're OK to remove GA for now. We can always reintroduce it at a later date if someone comes up with a value proposition.
