### ISSUE TITLE
Transfer ownership of domain

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint.io#66]
Hi @stylelint/core :wave: 

I just paid to renew the domain stylelint.io for another year. I'd like to transfer ownership of this domain to something controlled by the group that is maintaining the project, as I am no longer actively involved. How would you like to arrange this?

**Comment by ntwb** [comment]
Thanks David, I've started a follow up discussion here:

https://github.com/orgs/stylelint/teams/owners/
