### ISSUE TITLE
Improve changelog Table of Content

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint.io#69]
Currently all links looks like “[10.1.0][]”.

> Yes, it's strange. When I research it, I find that the behavior is due to the internal code of `docusaurus` and `markdown-toc`. See below:
> 
> - https://github.com/facebook/docusaurus/blob/v1.11.1/packages/docusaurus-1.x/lib/core/toc.js#L29
> - https://github.com/jonschlinkert/markdown-toc/blob/1.2.0/index.js#L209

_Originally posted by @ybiquitous in https://github.com/stylelint/stylelint.io/pull/67#issuecomment-509704539_

https://stylelint.io/changelog/

**Comment by ybiquitous** [comment]
I get the 2 solution ideas below:

- Change directly the [original `CHANGELOG` file](https://github.com/stylelint/stylelint/blob/2221d6edb4ebdd6f510a50889ec8cf5a8a48aed0/CHANGELOG.md). This seems to be simple, but it may be necessary to change other files such as [`docs/developer-guide/pull-requests.md`](https://github.com/stylelint/stylelint/blob/2221d6edb4ebdd6f510a50889ec8cf5a8a48aed0/docs/developer-guide/pull-requests.md).
- Change the generated `CHANGELOG` content via [`generate-stylelint-docs.js`](https://github.com/stylelint/stylelint.io/blob/ab19fd110484062961d06117f69aacb88c0c0e0f/scripts/generate-stylelint-docs.js). For example:

    ```diff
    -## [10.1.0](https://github.com/stylelint/stylelint/compare/10.0.1...10.1.0)
    +## 10.1.0
    +
    +See [full log](https://github.com/stylelint/stylelint/compare/10.0.1...10.1.0).
    ```

I think it would be better if we could change Docusaurus behavior, but I don't have a good idea to realize it now… 😓

**Comment by hudochenkov** [comment]
Will be automatically fixed with the next stylelint release.

**Comment by ybiquitous** [comment]
Nice! 👏
