### ISSUE TITLE
Improve meta description

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint.io#70]
`<meta name="description">` and `<meta property="og:description">` has weird content. On current website they are also incorrect.

> It seems to be a Docusaurus's bug. A description of doc pages is generated from the first line of the markdown content. See below:
>
> - https://github.com/facebook/docusaurus/blob/v1.11.1/packages/docusaurus-1.x/lib/core/DocsLayout.js#L92
> - Related issue: https://github.com/facebook/docusaurus/issues/1066

_Originally posted by @ybiquitous in https://github.com/stylelint/stylelint.io/pull/67#issuecomment-509710619_

**Comment by AoDev** [comment]
Hello, I'd like to suggest that the description could be set as pure text from front matter.
Example:
```markdown
---
id: some_page
title: "Some Page"
description: "This description will be set in the corresponding meta tag."
---
...page content...
```
My pages description don't make any sense at the moment, like:

``` 
<h2><a class="anchor" aria-hidden="true" id="install">
</a><a href="#install" aria-hidden="true" class="hash-link">
<svg class="hash-link-icon" aria-hidden="true" height="16" version="1.1" viewBox="0 0 16 16" width="16">
<path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path>
</svg>
</a>
Install</h2>

```

**Comment by ybiquitous** [comment]
https://github.com/facebook/docusaurus/issues/1066 was fixed. I expect a new version will be released soon. 😃

**Comment by ybiquitous** [comment]
Docusauru 1.12.0 has been released:

> fix: dont render html for meta description ([#1672](https://github.com/facebook/docusaurus/pull/1672))

https://github.com/facebook/Docusaurus/blob/v1.12.0/CHANGELOG.md#1120---2019-07-20

Thus, when triggering a new deploy build, the issue will be resolved automatically.

https://github.com/stylelint/stylelint.io/blob/ab19fd110484062961d06117f69aacb88c0c0e0f/website/package.json#L12

**Comment by ybiquitous** [comment]
I triggered a new deploy now:
https://app.netlify.com/sites/stylelint/deploys/5d37393a5821cfde443c600b

**Comment by ybiquitous** [comment]
The deploy finished. The following seems good to me:

https://stylelint.io/
![image](https://user-images.githubusercontent.com/473530/61730766-04a32f80-adb5-11e9-9cbe-a71475b1304b.png)

**Comment by hudochenkov** [comment]
Nice!
