### ISSUE TITLE
Migrate to Netlify

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint.io#72]
We're [thinking](https://github.com/stylelint/stylelint.io/pull/67#issuecomment-509865452) to migrating from Github Pages to Netlify. Reasons are:

* we can migrate to Docusaurus and don't break links. Github Pages doesn't support redirects.
* we could have deployment previews for PRs. Each PR could be automatically built and deployed for a preview.
* simplify deployment. Commit to master → automatic deploy. Currently we have to run `npm run deploy` from local machine.

Netlify has [Open Source Plan](https://www.netlify.com/legal/open-source-policy/).

@stylelint/core what do you think?

@ntwb you're usually has something to say when we want to change infrastructure :)

**Comment by hudochenkov** [comment]
Plan is to migrate to Netlify with current setup and use https://github.com/stylelint/stylelint.github.io as source for deployment. Then migrate this repository to Docusaurus completely (with removing Phenomic) and then change Netlify to run on this repository.

**Comment by evilebottnawi** [comment]
> simplify deployment. Commit to master → automatic deploy. Currently we have to run npm run deploy from local machine.

Good feature

Sounds very good

**Comment by ntwb** [comment]
Go for it, does stylelint need to apply for the open source plan?

Any credentials required, passwords, api keys, tokens etc I'd like a copy of them so that we can store them for the team in the stylelint 1Password team we have.

We will need to include the following:
Via https://www.netlify.com/legal/open-source-policy/
> _"In exchange for this free service, we request that you place a link to our service on your main page. We have premade badges for your convenience, or you may create your own link."_

**Comment by hudochenkov** [comment]
> Plan is to migrate to Netlify with current setup and use https://github.com/stylelint/stylelint.github.io as source for deployment.

This part is done. Now stylelint.io is deployed from https://github.com/stylelint/stylelint.github.io by Netlify. SSL also by Netlify (was Cloudflare). DNS is still managed by Cloudflare.

I didn't request Open Source plan yet. So I'm the only one who has access to Netlify at the moment. Will do when we deploy new website, where we can add link to Netlify as per their terms. Then we can create a new team and add more members.

**Comment by hudochenkov** [comment]
After migration following URLs were converted to lowercase and doesn't work at the moment when navigate directly. They do work when navigate by links on a page. It won't be an issue with Docusaurus.

https://stylelint.io/CHANGELOG/
https://stylelint.io/CONTRIBUTING/
https://stylelint.io/VISION/

Netlify converts case: https://community.netlify.com/t/my-url-paths-are-forced-into-lowercase/1659

**Comment by ybiquitous** [comment]
Nice work!

How about adding redirect rules to avoid 404? Until Docusaurus version will be shipped.

**Comment by hudochenkov** [comment]
It will create a loop. changelog → CHANGELOG (in redirects), then Netlify automatically redirect CHANGELOG → changelog. And it will start again.

**Comment by ybiquitous** [comment]
Oh, it's a bad idea, sorry... 😓

**Comment by hudochenkov** [comment]
I deployed a fix. I used last pre-Docusaurus commit, because it has correct remarks version. Then I changed `copy-stylelint-docs.js` to lowercase files:

```diff
// Copy root files (README, CHANGELOG, VISION etc)
const rootFiles = glob.sync("node_modules/stylelint/*.md");
rootFiles.forEach(function(file) {
-  fs.copySync(file, `content/${path.basename(file)}`);
+  fs.copySync(file, `content/${path.basename(file).toLowerCase()}`);
});
```

And then deployed.
