### ISSUE TITLE
Apply for Netlify Open Source Plan

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint.io#75]
We have a new website! It's [live](https://stylelint.io/)! Thank you @ybiquitous!

![GIF with a happy parrot](https://media.giphy.com/media/LZElUsjl1Bu6c/giphy.gif)

Last step is to apply to Netlify's [Open Source Plan](https://www.netlify.com/legal/open-source-policy/) to add access to Netlify for more than one person.

I'm going to take care of it.

**Comment by hudochenkov** [comment]
We're on Open Source Plan now! I've invited @ntwb, @jeddy3, @m-allanson already. @ybiquitous could you send me your email to my email (visible in my profile), so I can add you.

**Comment by ybiquitous** [comment]
@hudochenkov Thanks you so much! I sent you an email, please check it!
