### ISSUE TITLE
Fix random failing builds

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint.io#78]
Netlify builds are failing randomly:

https://app.netlify.com/sites/stylelint/deploys/5d2c363380d765b796fc1030
https://app.netlify.com/sites/stylelint/deploys/5d2b55026050c900084bc30e

And error logs looks strange. In the middle of `generate-stylelint-docs.js` output we get:

> failed during stage 'building site': Build script returned non-zero exit code: 1

Restarting the build doesn't help, but build with clean cache helps.

Maybe the problem because of `async` in this line (there is no `await` later):

https://github.com/stylelint/stylelint.io/blob/b22c63ab2b00049714b18be09aede83b4e443b07/scripts/generate-stylelint-docs.js#L83

@ybiquitous what do you think?

**Comment by ybiquitous** [comment]
Oh, sorry. The `async` is unnecessary. 😅 
I'll open a new PR soon. 👍
