### ISSUE TITLE
Update Travis CI NodeJS version

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint.io#8]
Currently Travis CI is configured with the alias `stable`, this is alias is deprecated, this currently results in testing NodeJS v5.11.0 even though v6.0.0 is now considered the most recent stable/current release

https://github.com/stylelint/stylelint.io/blob/master/.travis.yml#L5

Either `4` for the latest 4.x branch, or `6` for the current 6.x branch (6.0.0 was released overnight), it's not a new branch, just a major semver bump of the `current` branch, which was renamed from `stable` as part of this releas. _Alias naming is clear as mud!_

> Node.js v5 will continue to be supported for the next two months in order to give developers currently using v5 time to transition to Node.js v6. - https://nodejs.org/en/blog/release/v6.0.0/

I'm pretty sure we just want to change it to `6` here.

**Comment by jeddy3** [comment]
Thanks. Done in https://github.com/stylelint/stylelint.io/commit/62c25ddd7385217caeedcf14f2dd788414c84338
