### ISSUE TITLE
Show line numbers and collapse json

### ISSUE THREAD

**Issue by chinesedfan** [stylelint/stylelint.io#81]
They are my 2 suggestions for [Demo](https://stylelint.io/demo) page.

- Without line numbers for source codes, it is hard to find which line the error points to.
- With a better JSON editor, it will be easier to edit the stylelint config.

**Comment by ybiquitous** [comment]
Hi, the demo is hosted on another repo:
https://github.com/stylelint/stylelint-demo

**Comment by chinesedfan** [comment]
Oops, it is better for Github to have the ability to migrate issues. :)
