### ISSUE TITLE
Add external articles section

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint.io#9]
Wondering if we should link to some external articles?

e.g:
• https://css-tricks.com/stylelint/
• http://www.sitepoint.com/improving-the-quality-of-your-css-with-postcss/

**Comment by ntwb** [comment]
And/or maybe an [awesome](https://github.com/sindresorhus/awesome) repo `awesome-stylelint`, similar to [ESLint's](https://github.com/dustinspecker/awesome-eslint)?

Then adding repo's like https://github.com/packagesmith/provision-stylelint to that list as I'm not entirely sure repos such as `provision-stylelint` should be on the [user-guide/complementary-tools](http://stylelint.io/user-guide/complementary-tools/) page.

**Comment by jeddy3** [comment]
I think an articles page in the docs is the way forward, so it is generated on the website. 

If you think that's a good idea, feel free to open an issue in the main repo.

**Comment by ntwb** [comment]
Done, there's some issues with that `provision-stylelint` package so I won't add it until they are fixed
