### ISSUE TITLE
Please add optional dark theme

### ISSUE THREAD

**Issue by vitaly-zdanevich** [stylelint/stylelint.io#90]
Please read https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

Many users want to read it at night, also dark theme is better for battery of mobile phone.

**Comment by hudochenkov** [comment]
To be honest I don't see that it would be very useful. I'm looking at websites of other popular open-source tools, and can't find any which has this switch.

**Comment by vitaly-zdanevich** [comment]
But this is basic accessibility, a lot of people have sensitive eyes when it hurts to stairs at white screen. iOS recently introduced dark mode for the same reason, as many other products (YouTube, Evernote, Windows).

**Comment by ntwb** [comment]
I’m going to close this, there are many sites with a dark theme, GitHub to name just one, one day we may change the theme, and i”m sure we’ll consider this then. 

For now, I’m closing this and of course we’re always open to pull requests.

**Comment by jeddy3** [comment]
> For now, I’m closing this and of course we’re always open to pull requests.

We'll be getting [dark mode for free-ish](https://v2.docusaurus.io/docs/installation#scaffold-project-website)\* when Docusaurus V2 is out of alpha:

> The classic template contains @docusaurus/preset-classic which includes standard documentation, a blog, custom pages, and a CSS framework (__with dark mode support__).

@vitaly-zdanevich I not sure when Docusaurus V2 will be out of alpha, but dark mode will come to the stylelint website then.

\* "Free-ish" as we'll likely need to roll our own dark mode for [stylelint-demo](https://github.com/stylelint/stylelint-demo). I'm a fan of dark mode and can likely pick up this bit of work.
