### ISSUE TITLE
Netlify fails to deploy

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint.io#92]
Every PR, every merge, Netlify fails to deploy unless cache was cleared.

https://app.netlify.com/sites/stylelint/deploys/5d934071025d600009064978

**Comment by ntwb** [comment]
I merged the dependency PRs, cleared the cache at Netifly and redeploying now

**Comment by ntwb** [comment]
Of note, after merging the Husky PR, Netifly successfully deployed:

https://app.netlify.com/sites/stylelint/deploys/5d93ebb07de458000852730e
